# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

   pod 'SDWebImage', '~> 4.0'
   pod 'MBProgressHUD', '~> 0.9.1'
   pod 'HCSStarRatingView', '~> 1.5'
   pod 'RMPZoomTransitionAnimator', '~> 1.0.3'
  # Pods for TestProject

  target 'TestProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestProjectUITests' do
      # inherit! :search_paths
    # Pods for testing
  end

end
